### ISSUE TITLE
GATK custom pipeline error in gatk4cnsToBB.py 

### ISSUE THREAD

**Issue by asangphukieo** [raphael-group/hatchet#112]
Hi,

I can run GATK custom pipeline with the the example data (e.g. sample1.GATK4.CNV.seg and sample2.GATK4.CNV.seg).

When I try running the pipeline again with the data generated from GATK cnv tutorial (https://console.cloud.google.com/storage/browser/gatk-tutorials/workshop_2002/3-somatic/cna_precomputed;tab=objects?organizationId=548622027621&project=broad-dsde-outreach&prefix=&forceOnObjectsSortingFiltering=false), I get error in gatk4cnsToBB.py step.

Error
#################
#Parsing and checking input arguments
#Reading input files
#Segmenting all samples jointly
Traceback (most recent call last):
  File "/home/apiwat/HATCH/gatk4cnsToBB.py", line 222, in <module>
    main()
  File "/home/apiwat/HATCH/gatk4cnsToBB.py", line 73, in main
    segs = jsegmentation(segs)
  File "/home/apiwat/HATCH/gatk4cnsToBB.py", line 146, in jsegmentation
    log('##Coverage from joint segmentation is {0:.2f}%'.format(float(100.0 * cov) / tot))
ZeroDivisionError: float division by zero
Command exited with non-zero status 1
#################

I notice that some of the used columns in the segmentation file are NA.
I am curious how you make the sample1.GATK4.CNV.seg file. Can I have the your script of the GATK pipeline to reproduce this file?

**Comment by simozacca** [comment]
Thank you for your feedback; could you please share all or part of your segmentation file to help addressing the issue?

**Comment by asangphukieo** [comment]
[sample.zip](https://github.com/raphael-group/hatchet/files/7948217/sample.zip)
These are the segmentation files, I have done using GATK CNA pipeline.
Thank you for your help simozacca.

**Comment by simozacca** [comment]
@asangphukieo Sorry for the delay. Your segmentation files seem to have `NaN` values for the required field `MINOR_ALLELE_FRACTION_POSTERIOR_50`. Please compare your files with the examples [sample1.GATK4.CNV.seg](https://github.com/raphael-group/hatchet/blob/master/custom/GATK4-CNV/sample1.GATK4.CNV.seg) and [sample2.GATK4.CNV.seg](https://github.com/raphael-group/hatchet/blob/master/custom/GATK4-CNV/sample2.GATK4.CNV.seg) within the folder [GATK4-CNV](https://github.com/raphael-group/hatchet/tree/master/custom/GATK4-CNV).

BAF is required by HATCHet so the mentioned field must be present and computed by GATK. If you can fix this with the GATK pipeline but you still have issues, or if you have any further question, please let us know and feel free to re-open this issue.
