### ISSUE TITLE
GC correction

### ISSUE THREAD

**Issue by wir963** [raphael-group/hatchet#115]
I've noticed that most CN tools perform sequence GC content correction but I don't see any references to it in the HATCHet documentation. Is performing GC-correction suggested for HATCHet? If not, why not? Are there certain situations in which you would or would not recommend performing GC correction?

Best, Welles

**Comment by simozacca** [comment]
Thank you for your question. Currently, HATCHet is using the matched-normal sample to correct GC biases, please find additional details in the supplementary information of the related manuscript. In the coming updated versions of HATCHet, we plan to introduce the possibility to further add additional GC corrections for samples with particularly elevated GC-content bias and we will update once this feature will be integrated.
