### ISSUE TITLE
Hg38 not recognized

### ISSUE THREAD

**Issue by mdiaz09** [raphael-group/hatchet#120]
I am using hg38 as the reference genome but when changing the .ini reference to 
reference=hg38
I encounter the error 
ValueError: No SNPs found in the normal!
but changing it to reference=hg19 leads to the program running to completion.

**Comment by simozacca** [comment]
Thank you for your questions. Your issue seems to indicate a mismatch in the chromosome name notation that is used, i.e., no-`chr` vs `chr` version.
Could you please try to change the value of the following variable in your ini file?
```ini
# Does your reference name chromosomes with "chr" prefix?; True or False
chr_notation = True
```

**Comment by mdiaz09** [comment]
I appended the ini to add `chr_notation=True` or `chr_notation =False` and got the same issue

**Comment by simozacca** [comment]
Could you please share the header of your BAM file, that you could generate with the commnad `samtools view -H ${BAM}` where `${BAM}` is one of your tumour samples?

**Comment by mdiaz09** [comment]
The header is attached
[bamheader.txt](https://github.com/raphael-group/hatchet/files/8247248/bamheader.txt)

**Comment by simozacca** [comment]
Unfortunately the header does not seem to include information about the alignment, and the corresponding reference genome, which is problematic.

I would reccommend to try running BCFtools manually on your BAM file using either the SNP positions expected for hg19 or hg38 (for example, based on dbSNP), and check that SNPs are where we would expect for hg38. If that is not the case for hg38 but for hg19, then there might be an issue with your BAM file (possibly a re-alignment to hg19?).

You can achieve the two goals above with the following commands, assuming that `${BAM}` is your BAM file and that `${REF}` is the reference genome of your BAM file:

- For hg19:

```shell
﻿bcftools mpileup ${BAM} -Ou -f ${REF} --skip-indels --ignore-RG -T https://ftp.ncbi.nih.gov/snp/organisms/human_9606_b151_GRCh37p13/VCF/GATK/00-All.vcf.gz | bcftools call -mv -Oz -o snps.hg19.vcf.gz
```

- For hg38:

```shell
﻿bcftools mpileup ${BAM} -Ou -f ${REF} --skip-indels --ignore-RG -T https://ftp.ncbi.nih.gov/snp/organisms/human_9606_b151_GRCh38p7/VCF/GATK/00-All.vcf.gz | bcftools call -mv -Oz -o snps.hg38.vcf.gz
```

**Comment by EvaPang2022** [comment]
@mdiaz09 Hi I encountered the same issue. May I know whether you have solved it? Thanks!

**Comment by EvaPang2022** [comment]
Update 20220629
Possible solution:
In my case, I am using hg38 with chr prefix. The code will select this link to download the snp file. ('https://ftp.ncbi.nih.gov/snp/organisms/human_9606_b151_GRCh38p7/VCF/GATK/00-All.vcf.gz' , can see in hatchet/lib/python3.9/site-packages/hatchet/utils/run.py). But I guess for some reasons this link is invalid and a blank  00-All.vcf.gz is download,  which results in 'no snps called in normal bam'.

Under this situation, I solved the issue by downlaoding the 00-All.vcf.gz file manually and changed the path in run.py.  Or you can use other germline variant calling methods to call SNPs in the normal bam files, then setting snps parameter in hatchet.ini file.

**Comment by mdiaz09** [comment]
@EvaPang2022 
your solution worked for me. Thank you!
