### ISSUE TITLE
Possible bug?

### ISSUE THREAD

**Issue by vineetbansal** [raphael-group/hatchet#121]
I think `config.paths.tabix` here should have been `config.paths.picard` instead? (I see an entry added for picard in `hatchet.ini`)

https://github.com/raphael-group/hatchet/blob/9fe16fc0607cf38e541898e36fab74d183a32232/src/hatchet/utils/ArgParsing.py#L509

**Comment by mmyers1** [comment]
Fixed in commit `0ecb0713d0824fce4266a2eb1c2d10f056d87881` on `abin` branch
