### ISSUE TITLE
Code that will crash in certain circumstances

### ISSUE THREAD

**Issue by vineetbansal** [raphael-group/hatchet#128]
Contrary to what the comment around this line says, I don't see how each worker starts 2 processes (each worker is starting 3 processes, each of which are piped, so they have to sit on the same processor). In any case, if `processes=1` (which is a reasonable input), `n_workers_samtools` becomes `0`, and this code is never run.

https://github.com/raphael-group/hatchet/blob/eb696ce9ff40655a0119cabae7fdcdb4e61a22e1/src/hatchet/utils/count_reads.py#L54

If the intention here was to accommodate hyperthreading or something, then that's a processor design detail and should not be part of any python code.

**Comment by mmyers1** [comment]
Your fix in #132 looks good.
