### ISSUE TITLE
ArgParsing Bug

### ISSUE THREAD

**Issue by pkMyt1** [raphael-group/hatchet#13]
Line 387 in ArgParsing.py should be sp.error(..., not error(...

**Comment by simozacca** [comment]
Thank you for this correction! 

We will integrate it soon after the ongoing merging of the PR for CI branch and I will keep this issue open in the meanwhile.

**Comment by vineetbansal** [comment]
This is fixed in commit 8890e8ce021e75a00ed38e5dd9b4631a80c47c35 (hatchet version 0.1.0)
