### ISSUE TITLE
Is this correct?

### ISSUE THREAD

**Issue by vineetbansal** [raphael-group/hatchet#131]
AFAIK, '|' doesn't need to be escaped and '\\|' will look for a backslash followed by a pipe. If that's not the intention here, this may need investigating.

https://github.com/raphael-group/hatchet/blob/eb696ce9ff40655a0119cabae7fdcdb4e61a22e1/src/hatchet/utils/combine_counts.py#L163

**Comment by mmyers1** [comment]
By default `pandas.str.contains` treats the first argument as a regex, hence the escape character. It's probably clearer to use `regex=False` instead.

**Comment by mmyers1** [comment]
Addressed in commit 1159c2adee09245c387a0c150de8dc16d81aa054
