### ISSUE TITLE
multiple -i arguments found whilst running hatchet.py

### ISSUE THREAD

**Issue by gg10** [raphael-group/hatchet#2]
Hi,

I am trying to run hatchet in my dataset but i got an error whilst running HATCHet.py. The error trace is attached. Would you have an idea what I am doing wrong?

Thank you so much,
Gunes Gundem

/Users/gundemg/Documents/projects/neuroblastoma/triple_callers/error_trace.txt

**Comment by gg10** [comment]
selene:results gundemg$ python2 /ifs/work/leukgen/home/gg10/soft/libraries/hatchet-master/bin/HATCHet.py /ifs/work/leukgen/home/gg10/soft/libraries/hatchet-master/build/solve -i /ifs/res/papaemme/users/gg10/mycn_amplified_nbl/data/patient_I-H-112908/hatchet/bbc/bulk -n2,8 -p 400 -j 50 -v 3 -u 0.03 -r 12 -j 8 -eD 6 -eT 12 -g 0.35 -l 0.6
# Checking and parsing input arguments
## M:	2
## mR:	0.1
## mB:	0.05
## m:	None
## clonal:	None
## tR:	0.04
## seg:	/ifs/res/papaemme/users/gg10/mycn_amplified_nbl/data/patient_I-H-112908/hatchet/bbc/bulk.seg
## tetraploid:	False
## diploid:	False
## eT:	12
## r:	12
## tB:	0.03
## u:	0.03
## x:	./
## f:	None
## d:	None
## g:	0.35
## solver:	/ifs/work/leukgen/home/gg10/soft/libraries/hatchet-master/build/solve
## ln:	2
## eD:	6
## j:	8
## bbc:	/ifs/res/papaemme/users/gg10/mycn_amplified_nbl/data/patient_I-H-112908/hatchet/bbc/bulk.bbc
## ts:	0.02
## p:	400
## s:	None
## un:	8
## limit:	0.6
## v:	3
## input:	/ifs/res/papaemme/users/gg10/mycn_amplified_nbl/data/patient_I-H-112908/hatchet/bbc/bulk
## td:	0.1
## ampdel:	True
## tc:	1
# Reading and parsing clustered bins in BBC file
# Reading and parsing bin clusters in SEG file
# Computing the cluster sizes
# Filtering clusters based on covered genome size and covered chromosomes
### Clusters and their features:
### 10: SIZE= 980895122.0	#CHRS= 18	(RDR, BAF)= (1.57924648715, 0.48648579628)-(1.22030475421, 0.35648506399)
### 36: SIZE= 717500000.0	#CHRS= 16	(RDR, BAF)= (1.70250903965, 0.5)-(1.53261777354, 0.5)
### 32: SIZE= 389200000.0	#CHRS= 11	(RDR, BAF)= (1.91715316654, 0.486863052364)-(1.9275673641, 0.403002458644)
### 33: SIZE= 122500000.0	#CHRS= 10	(RDR, BAF)= (1.88622512303, 0.413861089193)-(1.90897999154, 0.234101879975)
### 17: SIZE= 104600000.0	#CHRS= 3	(RDR, BAF)= (1.33137541839, 0.340770425239)-(0.871997364185, 0.105588311854)
### 38: SIZE= 63550000.0	#CHRS= 4	(RDR, BAF)= (1.46958703287, 0.417425663942)-(0.87728893965, 0.477467823496)
### 4: SIZE= 54550000.0	#CHRS= 3	(RDR, BAF)= (2.50323237216, 0.341890163131)-(2.86010577138, 0.270523885872)
### 25: SIZE= 31500000.0	#CHRS= 17	(RDR, BAF)= (1.71673895842, 0.386158394748)-(1.54288094871, 0.3804316049)
### 18: SIZE= 22500000.0	#CHRS= 2	(RDR, BAF)= (2.47674552682, 0.324866535883)-(2.9361685992, 0.14839121037)
### 23: SIZE= 18350000.0	#CHRS= 4	(RDR, BAF)= (2.1197886788, 0.401172967198)-(2.23455091095, 0.352533809274)
### 29: SIZE= 16550000.0	#CHRS= 1	(RDR, BAF)= (1.62773351239, 0.497993620691)-(1.84789351489, 0.409286818686)
### 26: SIZE= 14850000.0	#CHRS= 1	(RDR, BAF)= (1.87042679957, 0.41862872666)-(1.552727741, 0.278259794486)
### 35: SIZE= 14288663.0	#CHRS= 9	(RDR, BAF)= (1.81741921826, 0.41597013101)-(1.82565347887, 0.292506920825)
### 21: SIZE= 12550000.0	#CHRS= 2	(RDR, BAF)= (2.69394895119, 0.367860990418)-(2.89837355762, 0.27270361322)
### 39: SIZE= 12550000.0	#CHRS= 13	(RDR, BAF)= (1.54447717489, 0.322498427725)-(1.21780904043, 0.291575379273)
### 19: SIZE= 11900000.0	#CHRS= 1	(RDR, BAF)= (1.11479907567, 0.394717851861)-(0.522817759351, 0.174859993642)
### 16: SIZE= 11090365.0	#CHRS= 17	(RDR, BAF)= (1.88965143132, 0.40857807959)-(2.04996178405, 0.332875747281)
### 22: SIZE= 10800000.0	#CHRS= 12	(RDR, BAF)= (1.33452567206, 0.353256828835)-(0.871236620237, 0.238018283505)
### 9: SIZE= 4850000.0	#CHRS= 3	(RDR, BAF)= (1.48386285706, 0.301685655585)-(1.18751095851, 0.0790805976468)
### 24: SIZE= 4050000.0	#CHRS= 4	(RDR, BAF)= (2.30846510729, 0.368340169097)-(2.4876324449, 0.312158996806)
### 40: SIZE= 3599373.0	#CHRS= 18	(RDR, BAF)= (1.69553564543, 0.30625424881)-(1.52342092907, 0.259081215889)
### 27: SIZE= 3300000.0	#CHRS= 1	(RDR, BAF)= (1.64454318772, 0.496586530368)-(2.5169896701, 0.309616072318)
# Selected clusters: 10, 38, 17, 33, 32, 36, 4
## Features of selected clusters:
## 10: SIZE= 980895122.0	#CHRS= 18	(RDR, BAF)= (1.57924648715, 0.48648579628)-(1.22030475421, 0.35648506399)
## 38: SIZE= 63550000.0	#CHRS= 4	(RDR, BAF)= (1.46958703287, 0.417425663942)-(0.87728893965, 0.477467823496)
## 17: SIZE= 104600000.0	#CHRS= 3	(RDR, BAF)= (1.33137541839, 0.340770425239)-(0.871997364185, 0.105588311854)
## 33: SIZE= 122500000.0	#CHRS= 10	(RDR, BAF)= (1.88622512303, 0.413861089193)-(1.90897999154, 0.234101879975)
## 32: SIZE= 389200000.0	#CHRS= 11	(RDR, BAF)= (1.91715316654, 0.486863052364)-(1.9275673641, 0.403002458644)
## 36: SIZE= 717500000.0	#CHRS= 16	(RDR, BAF)= (1.70250903965, 0.5)-(1.53261777354, 0.5)
## 4: SIZE= 54550000.0	#CHRS= 3	(RDR, BAF)= (2.50323237216, 0.341890163131)-(2.86010577138, 0.270523885872)
# Finding the neutral diploid/tetraploid cluster
## Cluster selected as neutral (diploid/tetraploid) is 36
# Running diploid
## Running diploid with 2 clones
### Running command: /ifs/work/leukgen/home/gg10/soft/libraries/hatchet-master/build/solve /ifs/res/papaemme/users/gg10/mycn_amplified_nbl/data/patient_I-H-112908/hatchet/bbc/bulk -f  -e 6 -j 8 -p 400 -u 0.03 -r 12 -M 2 -v 2 -c 36:1:1 -n 2 -o ./results.diploid.n2
Traceback (most recent call last):
  File "/ifs/work/leukgen/home/gg10/soft/libraries/hatchet-master/bin/HATCHet.py", line 887, in <module>
    main()
  File "/ifs/work/leukgen/home/gg10/soft/libraries/hatchet-master/bin/HATCHet.py", line 188, in main
    diploidObjs = runningDiploid(neutral=neutral, args=args)
  File "/ifs/work/leukgen/home/gg10/soft/libraries/hatchet-master/bin/HATCHet.py", line 374, in runningDiploid
    results.append((n , execute(args, basecmd, n, outprefix), outprefix))
  File "/ifs/work/leukgen/home/gg10/soft/libraries/hatchet-master/bin/HATCHet.py", line 634, in execute
    raise RuntimeError(error("The following command failed: \n\t\t{}\nwith {}\n".format(cmd, buffer)))
RuntimeError: The following command failed: 
		/ifs/work/leukgen/home/gg10/soft/libraries/hatchet-master/build/solve /ifs/res/papaemme/users/gg10/mycn_amplified_nbl/data/patient_I-H-112908/hatchet/bbc/bulk -f  -e 6 -j 8 -p 400 -u 0.03 -r 12 -M 2 -v 2 -c 36:1:1 -n 2 -o ./results.diploid.n2
with ['\x1b[91mMultiple -i arguments found!\x1b[0m', '']

selene:results gundemg$ vim error_trace.txt
selene:results gundemg$ pwd
/ifs/res/papaemme/users/gg10/mycn_amplified_nbl/data/patient_I-H-112908/hatchet/results

**Comment by gg10** [comment]
Hi,
I tried both.
1. When I ran this inside the build directory:
`python2 /ifs/work/leukgen/home/gg10/soft/libraries/hatchet-master/bin/HATCHet.py solve -i ./bulk -n2,8 -p 400 -j 50 -v 3 -u 0.03 -r 12 -j 8 -eD 6 -eT 12 -g 0.35 -l 0.6`
I get the same error about multiple -i arguments being found.
2. When I ran the following command:
`solve ./bulk -f  -e 6 -j 8 -p 400 -u 0.03 -r 12 -M 2 -v 2 -c 36:1:1 -n 2 -o ./results.diploid.n2`
I got the same error: Multiple -i arguments found!
3. Finally when I make the suggested changes in argparse.cpp and run the comman again, i get this:
Argument: solve
Argument: ./bulk
Argument: -f
Argument: -e
Argument: 6
Argument: -j
Argument: 8
Argument: -p
Argument: 400
Argument: -u
Argument: 0.03
Argument: -r
Argument: 12
Argument: -M
Argument: 2
Argument: -v
Argument: 2
Argument: -c
Argument: 36:1:1
Argument: -n
Argument: 2
Argument: -o
Argument: ./results.diploid.n2
Multiple -i arguments found!

This is indeed curious. Thank you so much in advance.

Best,
Gunes

**Comment by simozacca** [comment]
I am very sorry for this strange issue but we will figure it out. My guess is that there are some differences across compilers in the initialization of C++11 dictionaries and, therefore, I applied some changes to make sure all the initializations are explicit. I also published a debugging version of the `Argparser` that we can use to figure out what is happening step-by-step. As such, I would suggest to do the following:

## First

Try to use the new version of the `Argparser` by pulling the new version of the repository, re-compiling the code, and re-running the code. More specifically, please use the following commands:

```shell
cd /ifs/work/leukgen/home/gg10/soft/libraries/hatchet-master/build/
git pull
make
./solve ./bulk -f -e 6 -j 8 -p 400 -u 0.03 -r 12 -M 2 -v 2 -c 36:1:1 -n 2 -o ./results.diploid.n2
```

## Second

If the new version of the `Argparser` still did not work, please try to use the debugging version and provide to me the complete output. More specifically, do the following:

```shell
cd /ifs/work/leukgen/home/gg10/soft/libraries/hatchet-master/build/
mv ../src/argparse.cpp ../src/argparse-temp.cpp
cp ../utils/argparse.cpp ../src/
make
./solve ./bulk -f -e 6 -j 8 -p 400 -u 0.03 -r 12 -M 2 -v 2 -c 36:1:1 -n 2 -o ./results.diploid.n2
```

Please let me know the results of these steps,
Thank you for your patience,

Best

**Comment by gg10** [comment]
The diagnosis is correct. I pulled the latest version and ran HATCHet.py without any problem.

**Comment by simozacca** [comment]
I am very happy the fix solved your issue, I will then close the issue for now and remove the debugging version of the `ArgParser` from the repository. Please feel free to re open the issue if problems continue.

If you have general questions or you need support/advice in running HATCHet (in addition to the explanations provided in the `demos`), please contact me.

**Comment by simozacca** [comment]
Please remember to keep HATCHet updated by pulling sometimes the new version of the repository since we may introduce minor fixes for some bugs, some of which may be reported by other members of the community.

Thank you,
Best

**Comment by gg10** [comment]
Sure thing. Thank you.

Cheers,
Gunes
