### ISSUE TITLE
Bioconda installs numpy >= 2.0 which is incompativle with HATCHet

### ISSUE THREAD

**Issue by simozacca** [raphael-group/hatchet#229]
Bioconda installs HATCHet with the new version of `numpy >= 2.0` which is however incompatible with the current version of HATCHet and most of the used packages.

Temporary solution is to force the installation of an older version of numpy:

```
conda config --add channels bioconda
conda config --add channels conda-forge
conda config --set channel_priority strict

conda create -n hatchet hatchet "bcftools==1.19" "samtools==1.19" "numpy<=1.26"
```
Note that bcftools and samtools versions are neede as per #227 

For a permanent fix, @mmyers1 could you please update accordingly the version of numpy in the Bioconda recipe?

**Comment by vineetbansal** [comment]
@simozacca - I'm opening up PR #230 for this. It might be a few iterations before its ready to be reviewed. I'll mark it ready for review when it is.

**Comment by vineetbansal** [comment]
HATCHeT 2.1.0 is now available on `bioconda` with the correct pinning of numpy

**Comment by simozacca** [comment]
Wonderful, thank you!
