### ISSUE TITLE
cluBB bnpy version issue

### ISSUE THREAD

**Issue by karini925** [raphael-group/hatchet#29]
Hello dear developers,

I've identified an issue while trying to run `\time -v python2 -m hatchet cluBB ${BB}bulk.bb -o ${BBC}bulk.seg -O ${BBC}bulk.bbc -e ${RANDOM} -tB 0.04 -tR 0.15 -d 0.08`

I've followed the instructions in the tutorial and receive the following error: 
```
16:50:50]'time -v python2 -m hatchet cluBB /cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Hatchet/p001/bb/bulk.bb -o /cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Hatchet/p001/bbc/bulk.seg -O /cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Hatchet/p001/bbc/bulk.bbc -e 28080 -tB 0.04 -tR 0.15 -d 0.08
ESC[1mESC[95m[2021-Jan-11 16:52:15]# Parsing and checking input arguments
ESC[0mESC[1mESC[95m[2021-Jan-11 16:52:15]# Reading the combined BB file
ESC[0mESC[1mESC[95m[2021-Jan-11 16:52:16]# Format data to cluster
ESC[0mESC[1mESC[95m[2021-Jan-11 16:52:16]# Clustering bins by RD and BAF across tumor samples
ESC[0mESC[92m[2021-Jan-11 16:52:16]## Loading BNPY
ESC[0mESC[92m[2021-Jan-11 16:52:24]## Clustering...
ESC[0mTraceback (most recent call last):
  File "/cluster/tools/software/python/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/cluster/tools/software/python/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/cluster/home/kisaev/python2env/lib/python2.7/site-packages/hatchet/__main__.py", line 43, in <module>
    globals()[command](args)
  File "/cluster/home/kisaev/python2env/lib/python2.7/site-packages/hatchet/utils/cluBB.py", line 29, in main
    mus, sigmas, clusterAssignments, numPoints, numClusters = cluster(points=points, output=args["outsegments"], samples=samples, clouds=clouds, K=args["initclusters"], sf=args["tuning"], restarts=args['restarts'])
  File "/cluster/home/kisaev/python2env/lib/python2.7/site-packages/hatchet/utils/cluBB.py", line 151, in cluster
    hmodel, Info = bnpy.Run.run(Data, 'DPMixtureModel', 'DiagGauss', 'memoVB', nLap=100, nTask=restarts, K=K, moves='birth,merge', ECovMat='eye', sF=sf, doWriteStdOut=False)
AttributeError: 'module' object has no attribute 'Run'
Command exited with non-zero status 255
```

This is due to the change in bnpy function naming shown at this commit:
https://github.com/bnpy/bnpy/commit/79062d91ff5d67250fd800adee98e205c1fc287b#diff-ba6a27f08b567cf80a70b88a32847ce969311c9ca20180b95dfed4420f9fc402

Due to the fact that BNPY does not use releases it's currently impossible to pin it at the proper version allowing me to run your tool. 

`Run` has now been renamed to `Runner` thus causing an error when I run cluBB.

---

In addition I believe there are a few spots in your documentation that are outdated leading to conflicting commands requiring to pass in a -by flag which is no longer valid

1.  https://github.com/raphael-group/hatchet/blob/master/doc/doc_clubb.md
2. https://github.com/raphael-group/hatchet/blob/master/doc/doc_runhatchet.md#clubb

Thank you for all your work maintaining this tool
Cheers! 
-Karin

**Comment by vineetbansal** [comment]
Hello @karini925 .. thanks for your investigation!

I see that we currently specify only `bnpy` as a dependency in `setup.py`, which as of right now `0.1.6` on PyPI (which will work correctly with our code). So just making sure - did you install `bnpy` manually by cloning their repo instead? Any particular reason you chose to do this? Just curious..

I see that they haven't bumped up their version from `0.1.6` (in addition to not putting up the wheels on PyPI after they made this change), so to avoid this error for others who might be following the same process, I can modify the code to check for an `ImportError` and do things correctly in both cases.

The Python 3 version of `bnpy` is on their repo, and we are in the final stages of releasing a Python 3 version of `hatchet` as well, so this problem will largely go away soon.

Thanks also for the 2 outdated documentation instances. I'm fixing those right away..

**Comment by vineetbansal** [comment]
@karini925 .. I see that there's a cleaner version for us to fix this, which is to use `bnpy.run` (the alias) instead of `bnpy.Run.run`. This will work correctly for both pre- and post- the commit you mention here.

**Comment by karini925** [comment]
Thanks so much for your quick response! I used these instructions for installation: https://bnpy.readthedocs.io/en/latest/installation.html

**Comment by simozacca** [comment]
The fixes have been merged into the master branch; please let us know if this fixed your issues. Thanks!

**Comment by karini925** [comment]
Yes it does, thanks again!
