### ISSUE TITLE
Update command for number of CPUs for Python3

### ISSUE THREAD

**Issue by simozacca** [raphael-group/hatchet#37]
With the switch to python3, the python command to automatically retrieve the maximum number of CPUs needs to be corrected:

https://github.com/raphael-group/hatchet/blob/461d889ca886b1812e2950d32f8a8d0a2c9c7df3/script/runHATCHet.sh#L14

**Comment by vineetbansal** [comment]
fixed in commit 0a5e42dc46ba61ba667178d5bbe89cea9e39ea05
