### ISSUE TITLE
Bioconda version does not support SNPCaller

### ISSUE THREAD

**Issue by simozacca** [raphael-group/hatchet#43]
The current version of HATCHet in `bioconda` does not support the command `SNPCaller` and results in the following message:

```shell
> python -m hatchet SNPCaller
The following commands are supported: binBAM deBAF comBBo cluBB BBot solve BBeval
```

**Comment by vineetbansal** [comment]
Hmm..I just installed `hatchet` from `bioconda` in a brand new environment and do see the command:
```
$ python -m hatchet --help
The following commands are supported: binBAM SNPCaller deBAF comBBo cluBB BBot solve BBeval
```
Probably some conflicting/parallel `hatchet` installations? Let's talk offline..
