### ISSUE TITLE
Demoes/Examples are pointing to the wrong python exec in bioconda env

### ISSUE THREAD

**Issue by simozacca** [raphael-group/hatchet#44]
The current demos point to `python3` but when using `bioconda` version of HATCHet this is incorrect and should be substituted with `python`, otherwise resulting in the error:
```shell
/camp/apps/eb/software/Anaconda3/2020.02/bin/python3: No module named hatchet
```

**Comment by vineetbansal** [comment]
My understanding is that for a conda environment, `python` and `python3` are just soft links to the actual python executable. This may also be related to issue #43
