### ISSUE TITLE
Samtools and bcftools are missing from bioconda environment

### ISSUE THREAD

**Issue by simozacca** [raphael-group/hatchet#45]
`samtools` and `bcftools` are missing from the bioconda environment of HATCHet. Please add both of those to the corresponding recipe.

**Comment by vineetbansal** [comment]
Submitted an update to the recipe..`samtools` and `bcftools` were installed by default anyway (probably by some other dependency), so I really think there's something going on in your conda environment.

**Comment by vineetbansal** [comment]
Done
