### ISSUE TITLE
deBAF required options inconsistent

### ISSUE THREAD

**Issue by jdm204** [raphael-group/hatchet#46]
Hi, thanks for this software!

I'm trying to run the `deBAF` step of the workflow, I provided `--regions` as my data are exome-based and get an error stating that the `--snps` option is required - I don't think this is documented [here](https://github.com/raphael-group/hatchet/blob/master/doc/doc_debaf.md). 

I made a snps file by extracting the chrs and positions from a gnomad VCF (no header, it's not complete clear what kind of file `deBAF` expects), but `parse_baf_arguments` errors with

```
ValueError: Both SNP list and genomic regions have been provided, please provide only one of these!
```
 For Exome data, should I subset the list of snps using my exon regions manually given that I can't pass both to the tool?

**Comment by jdm204** [comment]
The issue was that I didn't see the full script as the link from usage [404s](https://github.com/raphael-group/hatchet/blob/master/script/runHATCHet.sh) - once I cloned the repo and found `runUnphased.sh` I understood the steps.

**Comment by vineetbansal** [comment]
Thanks @jdm204 .. we have fixed the broken link to point to the new scripts folder (where we have scripts to run phased/unphased workflows for HATCHet). Thanks for bringing this to our attention!
