### ISSUE TITLE
GATK custom pipeline is using python2

### ISSUE THREAD

**Issue by simozacca** [raphael-group/hatchet#47]
The [GATK custom pipeline](https://github.com/raphael-group/hatchet/blob/master/custom/GATK4-CNV/gatk4cnsToBB.py) is using python2 and is not working in the new python3 environment of HATCHet and needs to move over python3.

**Comment by vineetbansal** [comment]
Fixed in commit 6696c8f23ca1e9165da3b9fd44b73eaefac8f972
