### ISSUE TITLE
GRBException Solve Step Failure

### ISSUE THREAD

**Issue by rgold97** [raphael-group/hatchet#52]
Hi! I have a WLS gurobi license and am wondering how to circumnavigate the errors I am getting at the solve step where it throws a GRBexception. I've set the GUROBI_HOME and GRB_LICENSE_FILE variables and have verified that my license is active… do you have any advice on this front? I had previously (old code ?) gotten the WES demo to run all the way through but I am once again getting this GRBexception error. 

Thanks so much!

**Comment by vineetbansal** [comment]
One relatively quick way to check whether the error you're encountering is a Gurobi License issue or a solver error particular to your specific case (i.e. the solver never converges) is to (assuming you have HATCHet installed in the environment where you're going to do this):

- clone the HATCHet repository
- cd `</path/to/hatchet/repo>`
- `pip install pytest`
- `pytest tests/test_solver.py`

This will run a quick Gurobi test on a very simple input - if this works correctly then your Gurobi license should also work in a real-life case, and probably the problem lies somewhere else.

**Comment by rgold97** [comment]
This test failed--any advice with this failure message? Is this a license error? Or something else?

![Screen Shot 2021-04-09 at 2 08 57 PM](https://user-images.githubusercontent.com/28493357/114222953-39ff0080-993d-11eb-80ee-f6a3798a90ae.png)

**Comment by rgold97** [comment]
![Uploading Screen Shot 2021-04-09 at 2.16.45 PM.png…]()
Not quite sure what this error is indicating--I definitely exported the GRB_LICENSE_FILE variable. Any ideas? Thanks!

**Comment by vineetbansal** [comment]
@rgold97 .. looks like your screenshot didn't come through?

**Comment by rgold97** [comment]
Whoops! Here you go:

![Screen Shot 2021-04-09 at 2 16 45 PM](https://user-images.githubusercontent.com/28493357/114283890-4dcc6480-9a1a-11eb-8091-2e162299eaf0.png)

**Comment by ybta2957e** [comment]
Hi, I have same error at the same step (solve step). It returns " terminate called after throwing an instance of 'GRBException' ".
I already have used `grbgetkey` to get new license and set it to environmental variable. I used the Anaconda3 to install hatchet.
![hatchet1](https://user-images.githubusercontent.com/60736407/115359241-12d3e900-a1f1-11eb-8f74-ff6e88eee44c.png)
![hatchet2](https://user-images.githubusercontent.com/60736407/115359243-14051600-a1f1-11eb-9fb4-56316fc52b4e.png)
![hatchet3](https://user-images.githubusercontent.com/60736407/115359664-7c53f780-a1f1-11eb-96e9-6d654e20a3e4.png)

**Comment by simozacca** [comment]
@ybta2957e could you please let us know whether you are using a computing cluster? `grbgetkey` can only be used to obtain the individual Gurobi license which is machine- and user-specific. If you are using a computing cluster (and not a server or local machine) then a different license is needed. Please check the related section in the documentation.

**Comment by ybta2957e** [comment]
Thanks for your reply,
I used the HPC, so I need the Multi-use license for running Gurobi?
