### ISSUE TITLE
Possible to convert BAF to 0-1 scale?

### ISSUE THREAD

**Issue by tomvdbosch** [raphael-group/hatchet#62]
Hi,

I would like to compare results from Hatchet to those that I got from other methods (SNP arrays). However, Hatchet gives BAF values from 0-0.5 which I assume is the ratio of major allele/minor allele, whereas SNP arrays usually output BAF between 0-1.
Is there a way to convert these values, e.g. can I just take the ratio's in the baf/tumor.bed file and then take the mean across a segment of 50k? 
Thanks in advance!

**Comment by simozacca** [comment]
Thank you for your question.

The BAF value of HATCHet actually corresponds to the Mirrored BAF `MBAF` which can be computed as `MBAF = min(BAF, 1 - BAF)` for standard definition of `BAF`.

If you want to compute the `MBAF` within a specific genomic region (or bin) containing multiple SNPs, there are two potential approaches that you can adopt, assuming that `A_i, B_i` are the read counts for every SNP `i` in the region:
1. `MBAF = ( \sum_i  \min(A_i, B_i) ) /  (\sum_i A_i + B_i)` which is the recommended and current approach adopted by HATCHet;
2. `MBAF = \average_i ( \min( B_i / (A_i + B_i), 1 - B_i / (A_i + B_i) ) ) ` which is similar to your proposed approach (even though the ratio at every position needs to be mirrored as described above) and is another generally used approach. However, this estimator tends to be more biased in general and is not reccomended.

Please find more related details on the Supplementary Information of the [published HATCHet's paper](https://doi.org/10.1038/s41467-020-17967-y).
Please let us know if you have any further question.
