### ISSUE TITLE
Bioconda update for v0.3.2

### ISSUE THREAD

**Issue by prateek-anand** [raphael-group/hatchet#71]
Hi,

I checked bioconda and HATCHet still seems to be on v0.3.1. Can you please update it? I would like to run some tests using the bug-fixed version.

Thanks.

Edit: Actually, that might just be the "Versions:" section that doesn't have v0.3.2 listed. Is it just missing there?

**Comment by vineetbansal** [comment]
Hi @prateek-anand .. `HATCHet 0.3.2` was pushed to `bioconda` a few days ago. I'm seeing it here as well as when creating a new environment:
https://anaconda.org/bioconda/hatchet

I see it in the 'Versions' dropdown too. Let me know where you expect to see it but don't, and I can investigate.

**Comment by prateek-anand** [comment]
Oh, looks like I was on a different site: https://bioconda.github.io/recipes/hatchet/README.html#package-hatchet

Here it says 0.3.1 in the versions section, but I do see v0.3.2 when I go to downloads.

**Comment by vineetbansal** [comment]
Good to know - I think that page may just be lagging behind in terms of indexing the latest package.

**Comment by prateek-anand** [comment]
Ok, thank you. I'll make sure to check the page you listed instead for future reference.
