### ISSUE TITLE
Type error in plot-cn

### ISSUE THREAD

**Issue by ardydavari** [raphael-group/hatchet#73]
https://github.com/raphael-group/hatchet/blob/81fa8ae42366a9e126da5c2f5095ebef5350673b/src/hatchet/utils/plot_cn.py#L45

Arg type is str, but later comparison requires int type.

https://github.com/raphael-group/hatchet/blob/81fa8ae42366a9e126da5c2f5095ebef5350673b/src/hatchet/utils/plot_cn.py#L90

**Comment by simozacca** [comment]
Thank you for catching the error! 

@vineetbansal could we please include this in the next release?

**Comment by vineetbansal** [comment]
@ardydavari  - this is now fixed in [HATCHet v0.3.3](https://github.com/raphael-group/hatchet/releases/tag/v0.3.3) (available on bioconda).

**Comment by simozacca** [comment]
The issue has been fixed in the last version. Please feel free to re-open the issue in case of additional questions or doubts.
