### ISSUE TITLE
Known samples with low purity - resolution of clone portion

### ISSUE THREAD

**Issue by ardydavari** [raphael-group/hatchet#75]
I was wondering if we have a known set of samples (J) with adequate purity and known set of samples (K) with low purity. If we first solve for the clonal profiles using just samples J, would it be possible to later calculate the proportions of clone1,2,3 etc for samples K?

**Comment by simozacca** [comment]
We assume that the answer was helpful to solve the issue. Please feel free to re-open this issue in case of additional questions or doubts.
