### ISSUE TITLE
How to pick the right copy number solution

### ISSUE THREAD

**Issue by ardydavari** [raphael-group/hatchet#76]
How reliable is the chosen copy number solution made by hatchet? Are there any suggested ways of confirming that it is the correct one, rather than a different solution with a larger number of subclones? Is it important that the maximum copy number across bins be below a specific maximum number? I noticed that this value varies among the different solutions.

I understand that the optimal solution is being chosen based on maximizing the score (the second derivative of the objective function). However the chosen solution seems like it found a dominant subclone which it declares to present in all samples, rather than a higher-order solution with greater heterogenity. Should this be used as a criteria as well?

Thank you

**Comment by simozacca** [comment]
Thank you for your questions and your interest in HATCHet!

Evaluating multiple solutions and adapting some parameters according to the features of the input datasets is a very important part of HATCHet, especially when considering relatively noisy sequencing datasets as those typically obtained from WES or low-coverage WGS. We have thus established some important guidelines to follow for guiding this process and considering the different parameters that can be tuned. Please take a look of these guidelines in the [Recommendation section](http://compbio.cs.brown.edu/hatchet/doc_fullpipeline.html#recommendations) of the documentation, especially to the guidelines [Analyze HATCHet inference]() and [Analyze different type of data](http://compbio.cs.brown.edu/hatchet/recommendation_datatype.html) related to your questions.

Importantly, please take also a look of the guided examples [demo-wgs-cancer](http://compbio.cs.brown.edu/hatchet/examples/demo-WGS-cancer/demo-wgs-cancer.html) and [demo-wes](http://compbio.cs.brown.edu/hatchet/examples/demo-WES/demo-wes.html), which show examples on how to improve the results and explore different solutions.

Furthermore, please note that HATCHet is outputting all the solutions inferred for all the evaluated number of clones both with or without WGD (by default within the folder `results`). Please read about these outputs in the description of the command [compute-cn](http://compbio.cs.brown.edu/hatchet/doc_compute_cn.html).

Lastly, please note that the command [plot-cn](http://compbio.cs.brown.edu/hatchet/doc_plot_cn.html) is used to generate summary plots for the best chosen solution by providing the file `best.bbc.ucn` in input, but it could be equally used to generate the [summary plots](http://compbio.cs.brown.edu/hatchet/doc_plot_cn.html) for any of the inferred solutions. For example, if you want to evaluate a solution with a higher number 5 of clones without WGD which is stored in the file `results.diploid.n5.bbc.ucn.tsv` you can generate the corresponding plots using the following command (several adjusting options are available please see them in the related documentation)
```shell
hatchet plot-cn results.diploid.n5.bbc.ucn.tsv
```
Therefore, you can use these different plots to evaluate the differences among different inferred solutions, especially solutions that had similar scores.

Please let us know if you have any further questions.

**Comment by simozacca** [comment]
We assume that the answer was helpful to solve the issue. Please feel free to re-open the issue in case of additional questions or doubts.
