### ISSUE TITLE
Samples in BBC files does not match the ones in SEG file

### ISSUE THREAD

**Issue by prateek-anand** [raphael-group/hatchet#77]
Hi,

I'm trying to run the full HATCHet script using three tumor samples (`L01`, `L02`, and `P01`), but I'm getting an error in the `compute-cn` step:

    Traceback (most recent call last):
      File "/mnt/exports/shared/home/panand/miniconda3/envs/hatchet/bin/hatchet", line 33, in <module>
        sys.exit(load_entry_point('hatchet==0.3.2', 'console_scripts', 'hatchet')())
      File "/mnt/exports/shared/home/panand/miniconda3/envs/hatchet/lib/python3.9/site-packages/hatchet/__main__.py", line 64, in main
        globals()[command](args)
      File "/mnt/exports/shared/home/panand/miniconda3/envs/hatchet/lib/python3.9/site-packages/hatchet/utils/run.py", line 149, in main
        hatchet_main(args=[
      File "/mnt/exports/shared/home/panand/miniconda3/envs/hatchet/lib/python3.9/site-packages/hatchet/bin/HATCHet.py", line 181, in main
        assert bsamples == ssamples, error("Samples in BBC files does not match the ones in SEG file!")
    AssertionError: Samples in BBC files does not match the ones in SEG file!

The input log for `compute-cn` looks like this:

    ## solver:	/mnt/exports/shared/home/panand/miniconda3/envs/hatchet/lib/python3.9/site-packages/hatchet/solve
    ## input:	output/bbc/bulk
    ## seg:	output/bbc/bulk.seg
    ## bbc:	output/bbc/bulk.bbc
    ## ln:	2
    ## un:	6
    ## clonal:	None
    ## ampdel:	True
    ## d:	None
    ## eD:	6
    ## eT:	12
    ## ts:	0.008
    ## tc:	1
    ## td:	0.01
    ## tR:	0.08
    ## tB:	0.04
    ## mR:	0.08
    ## mB:	0.04
    ## limit:	0.6
    ## g:	0.35
    ## p:	400
    ## j:	72
    ## r:	None
    ## s:	None
    ## m:	None
    ## u:	0.03
    ## f:	None
    ## M:	2
    ## x:	output/results
    ## diploid:	False
    ## tetraploid:	False
    ## v:	2

I tried printing out the contents of `bsamples` and `ssamples` right before the assertion during the run, and saw that ssamples was empty:

    bsamples: {'L01', 'L02', 'P01'}
    ssamples: set()

But when I run `compute-cn` separately using:

    hatchet compute-cn -i output/bbc/bulk -x output/results/ -n 2,6 -p 400 -u 0.03 -eD 6 -eT 12 -g 0.35 -l 0.6

it works as expected. 

I'm unsure where to look for this. Any help would be appreciated, thanks.

**Comment by vineetbansal** [comment]
Thanks @prateek-anand  - if the `compute-cn` step is running fine by itself but not when its a part of `run` it likely indicates a bug in the the `run` wrapper. Let me see if I can reproduce the behavior using some sample data on my end. I'll back to you in case I need some more information.

**Comment by vineetbansal** [comment]
@prateek-anand - there was indeed a bug that had to do with the previous step in the HATCHet pipeline (`compute-cn`) not closing the files it generated. This now fixed in [HATCHet v0.3.3](https://github.com/raphael-group/hatchet/releases/tag/v0.3.3) (available on bioconda).

**Comment by prateek-anand** [comment]
Thanks, I just updated to v0.3.3 and it now runs properly.
