### ISSUE TITLE
Impossible to specify --regions in count-alleles

### ISSUE THREAD

**Issue by jdm204** [raphael-group/hatchet#79]
Hi, I'm trying to run hatchet on WES data, but there doesn't seem to be a way to provide the `--regions` option to count-alleles,

in the arg parsing code, the `--snps` options is required

```
 parser.add_argument("-L","--snps", required=True, type=str, nargs='+', help="List of SNPs to consider in the normal sample")
```
but the parser exits if `--regions` is also specified.
```
if args.snps != None and args.regions != None:
      raise ValueError(sp.error("Both SNP list and genomic regions have been provided, please provide only one of these!"))
```
I copied the above code from master but I'm having the issue on Bioconda hatchet=0.3.2.

**Comment by simozacca** [comment]
Thank you for your question!

At this time HATCHet does not allow the user to provide both `regions` and `snps` files. 
The recommended usage for whole exome sequencing (WES) data is to run HATCHet in the default mode, without providing the `regions` file, but using larger bin sizes `size` (the suggested is `size=250kb`) and higher thresholds for the minimum/maximum numbers `mincov`, `maxcov` of SNP reads (this should depend on your sequencing coverage, but for an average of 200x the recommended values are `mincov=20` and `maxcov=1000`). 

Please find more details in the related [reccomendation section](http://compbio.cs.brown.edu/hatchet/recommendation_datatype.html) and a related WES example in the [WES demo](http://compbio.cs.brown.edu/hatchet/examples/demo-WES/demo-wes.html).

Please feel free to re-open the issue in case of additional questions or doubts.
