### ISSUE TITLE
Could the outcome from HATCHet link to MACHINA?

### ISSUE THREAD

**Issue by biosurgeon** [raphael-group/hatchet#8]
Hi, Thanks for the nice software and detailed/kind introduction to use. (I love the tutorial!!)

In the original paper for HATCHet, figure 7, it seemed that infer clonal seeding is possible via MACHINA algorithm with the outcome of HATCHet. 
https://www.biorxiv.org/content/10.1101/496174v1.full.pdf

I could run MACHINA with the outcome from Pyclone, but I don't know how to link the outcome from HATCHet to MACHINA.

If it is possible, could you add some details how to infer clonal seeding via MACHINA with the outcome of HATCHet in introduction of HATCHet?

or in the paper, it was just compared results from MACHINA and HATCHet with same data? not HATCHet to MACHINA?

Thanks!

==== updated==
I received comments from Gryte Satas as like below. It is helpful information to me, and I'll try it.

Thanks all !!

However, one could run MACHINA in phm_tr mode which takes as input a phylogeny and infers a seeding history while resolving polytomies in the input phylogeny. In order to do this, one must first infer a phylogeny using the HATCHET copy-number clones. This can be done with our Copy-Number Tree algorithm (https://github.com/raphael-group/CNT-ILP). The resulting phylogeny can then be used as input for MACHINA as described in the pmh_tr section of the documentation.

**Comment by simozacca** [comment]
Thank you for the interest in HATCHet and for the nice feedback about the documentation!

Figure 7 in the [preprint](https://www.biorxiv.org/content/10.1101/496174v1) of the HATCHet's manuscript is solely based on the results from HATCHet; MACHINA has not been applied there. More specifically, Figure 7 depicts the clonal compositions (each unique clone is represented by a color) inferred by HATCHet jointly across multiple samples. The interesting proposed analysis of that figure is to investigate tumor clones that are shared across multiple samples, as this provides important information about metastatic seeding patterns: for example, samples from the same patient that share more than two tumor clones (red arcs) suggest polyclonal migrations across these samples.

A more sophisticated and detailed analysis of metastatic seeding patterns can be done by using MACHINA; unfortunately, MACHINA only supports CNAs when a corresponding phylogenetic tree is provided. Using the CNAs inferred by HATCHet, one could use other methods to reconstruct a corresponding phylogenetic tree, for example [CNT](https://github.com/raphael-group/CNT-ILP) and use this tree for applying MACHINA to it. Please find more details in the related MACHINA [issue](https://github.com/raphael-group/machina/issues/12).

Please feel free to re-open the issue if you have any additional question.
