### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by TN-L** [raphael-group/hatchet#81]
Hello,
I have encountered a RuntimeError while running the pipeline, which is believed to occur in the compute-cn or plot-cn step as no results are written.
The error occurs in line 644 of HATCHet.py with the following error message:

```
## Cluster selected as neutral (diploid/tetraploid) is 9
# Running diploid
## Running diploid with 2 clones
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/hatchet/__main__.py", line 69, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/hatchet/__main__.py", line 63, in main
    globals()[command](args)
  File "/opt/conda/lib/python3.8/site-packages/hatchet/utils/run.py", line 151, in main
    hatchet_main(args=[
  File "/opt/conda/lib/python3.8/site-packages/hatchet/bin/HATCHet.py", line 192, in main
    diploidObjs = runningDiploid(neutral=neutral, args=args)
  File "/opt/conda/lib/python3.8/site-packages/hatchet/bin/HATCHet.py", line 381, in runningDiploid
    results.append((n , execute(args, basecmd, n, outprefix), outprefix))
  File "/opt/conda/lib/python3.8/site-packages/hatchet/bin/HATCHet.py", line 644, in execute
    raise RuntimeError(error("The following command failed: \n\t\t{}\nwith {}\n".format(cmd, buffer)))
RuntimeError: The following command failed: 
                /opt/conda/lib/python3.8/site-packages/hatchet/solve /scratch/887692/hatchet/output/bbc/bulk -f  -e 6 -j 4 -p 400 -u 0.03 -M 2 -v 2 -c 9:1:1 -n 2 -o /scratch/887692/hatchet/output/results/results.diploid.n2
with ['\x1b[95m\x1b[1m[10:48:58]### Parsing and checking input arguments\t\x1b[0m', '\x1b[92m[10:48:58]## \tInput prefix:  /scratch/887692/hatchet/output/bbc/bulk', 'Input SEG:  /scratch/887692/hatchet/output/bbc/bulk.seg', 'Input BBC:  /scratch/887692/hatchet/output/bbc/bulk.bbc', 'Number of clones:  2', 'Clonal copy numbers:  { 9 [Cluster] : 1|1 [CN] }', 'Help message:  0', 'Maximum number of copy-number states:  -1', 'Maximum integer copy number:  6', 'Number of jobs:  4', 'Number of seeds:  400', 'Minimum tumor-clone threshold:  0.03', 'Maximum resident memory:  -1', 'Time limit:  -1', 'Maximum number of iteratios:  10', 'Random seed:  -1', 'Solving mode:  Coordinate-descent only', 'Verbose:  2', 'Output prefix:  /scratch/887692/hatchet/output/results/results.diploid.n2', 'Diploid threshold:  0.1', 'Base:  1', 'Force amp-del:  1\t\x1b[0m', '\x1b[95m\x1b[1m[10:48:58]### Reading the input SEG file\t\x1b[0m', '\x1b[95m\x1b[1m[10:48:58]### Scale the read-depth ratios into fractional copy numbers using the provided copy numbers\t\x1b[0m', '\x1b[95m\x1b[1m[10:48:58]### Compute allele-specific fractional copy numbers using BAF\t\x1b[0m', '\x1b[95m\x1b[1m[10:48:58]### Starting coordinate descent algorithm on 400 seeds\t\x1b[0m', '\x1b[92m[10:48:58]## Coordinate Descence {\t\x1b[0m', "terminate called after throwing an instance of 'GRBException'", '']
```

I am using the latest version HATCHet 0.3.3 and the reference genome is HG19 / GRCh37.

Is there a possible fix for this?
Best wishes
Tim

**Comment by simozacca** [comment]
The exception `GRBException` that you received (see the end of the error message) indicates an issue with the required Gurobi license, please refer to these previous issues for guidance: https://github.com/raphael-group/hatchet/issues/78, #16 and #52

Please feel free to re-open the issue in case of further questions or problems.

**Comment by TN-L** [comment]
Thank you for your answer.
I have looked at the linked issues and also tried the individual steps. Unfortunately, I still get the same error. I have tried the following steps:
- New Gurobi license used
- Installing Gurobi Optimizer using conda and manually, setting the associated GUROBI_HOME
- I put the gurobi license in my home folder and set the GRB_LICENSE_FILE variable
- I use the test suggested in [#78](https://github.com/raphael-group/hatchet/issues/78) and I get the same error message as shown in the picture in [#78](https://github.com/raphael-group/hatchet/issues/78) if I set the GRB_LICENSE_FILE variable, even with the new gurobi license
- if I did not set the GRB_LICENSE_FILE variable the test is skipped

Translated with www.DeepL.com/Translator (free version)

**Comment by simozacca** [comment]
If the test in https://github.com/raphael-group/hatchet/issues/52 is failing this is highlighting an issue with the Gurobi license.

Could you please provide the details of the machine and platform that you are running on? For example, are you on a personal laptop, server, or computing cluster? Also, are you within a Docker?

`grbgetkey` can only be used to obtain the individual Gurobi license which is machine- and user-specific and you can thus using it only on a personal machine or static computing server. If you are using a computing cluster (and not a server or local machine) then a different license is needed. Please check the related section in the documentation.

**Comment by TN-L** [comment]
I am using my personal computer for testing hatchet and it runs Ubuntu 21.04. It runs directly on my machine without docker.

**Comment by simozacca** [comment]
Could you please check that your Gurobi license did not expire and you are using the same user that is executing the test? You can check this by reading within the license file. Also, could you please use `grbgetkey` to get a new license?

@vineetbansal do you have any other suggested test to figure out what is wrong with the license?

**Comment by TN-L** [comment]
My license was still valid, but it seems to have been corrupted during the check, despite repeated downloads. With a newer license the test runs through. Thank you very much for your help.
