### ISSUE TITLE
python -m hatchet run ?

### ISSUE THREAD

**Issue by chenxf611** [raphael-group/hatchet#90]
Hi, 

I am trying to run demo-complete, copied all files, and generated the hatchet.ini file. Then

python -m hatchet run hatchet.ini

>The following commands are supported: binBAM SNPCaller deBAF comBBo cluBB BBot solve BBeval

it seems there is no such a command called "run"

Did I miss something here?

Thanks

Jack

**Comment by chenxf611** [comment]
Never mind, I believe I somehow installed an older version of hatchet. I reinstalled it and now it works. 

Thanks

Jack

**Comment by simozacca** [comment]
The error indicates a problem with Gurobi's license, please see the previous related issues: #81, #78, #16 and #52.

The last version of HATCHet now includes a specific command to check that the selected solver is working properly and @vineetbansal can provide you more details on how to test it.

Also, please note that if you do not have access to a valid Gurobi license, now HATCHet supports a multitude of different solvers, including open source and free solvers, read more at http://compbio.cs.brown.edu/hatchet/README.html#installation

**Comment by vineetbansal** [comment]
@chenxf611 - we've just released `HATCHet 0.4.3` on `bioconda` which includes a `check-solver` command which should serve as a quick check to see if your solver is working correctly. If `hatchet check-solver` doesn't work, then it indicates a licensing issue. See http://compbio.cs.brown.edu/hatchet/README.html#using-a-solver on how to specify your Gurobi license, and how to use an alternative solver other than Gurobi.

In any case `hatchet check-solver` needs to work correctly before your `run` pipeline can be expected to work end-end.

**Comment by simozacca** [comment]
We assume that the issue has been solved. Please feel free to re-open it if needed.
