### ISSUE TITLE
Wrong error message (normal->tumor)

### ISSUE THREAD

**Issue by tyamaguchi-ucla** [raphael-group/hatchet#94]
Hi,

It looks like this error message is wrong. (normal should be tumor here)

` for tumor in tumors:
 if(not os.path.isfile(tumor)): raise ValueError(sp.error("The specified normal BAM file does not exist"))` 

https://github.com/raphael-group/hatchet/blob/c3a6894c6833c53a8316a88325cf93b7c5b71f47/src/hatchet/utils/ArgParsing.py#L231

**Comment by simozacca** [comment]
Thank you for your feedback! This is absolutely correct and we will fix it accordingly in the next release.

**Comment by vineetbansal** [comment]
@tyamaguchi-ucla - thanks. This error message is fixed in version 0.4.5 of HATCHet which should be available on bioconda later today.

**Comment by vineetbansal** [comment]
@tyamaguchi-ucla - error message fixed in HATCHet 0.4.6. Closing this now.
