### ISSUE TITLE
WXS demo doc

### ISSUE THREAD

**Issue by tyamaguchi-ucla** [raphael-group/hatchet#98]
Hi,

Thanks for the useful demo. http://compbio.cs.brown.edu/hatchet/examples/demo-WES/demo-wes.html

For this sentence, 
`--xmin 0 and --xmax 2 allow to zoom in and to focus the figure on the same RDR (x-axis) range for every sample.`
It looks like x-axis should be y-axis.

**Comment by simozacca** [comment]
Thank you for catching this! @brian-arnold or @mmyers1 could you please include this correction during the next merging? Thank you

**Comment by mmyers1** [comment]
Addressed in 27d046c6be2febffb5541b14c156d001f71f0b1d
